address:
	python newaddress.py

account:
	python account.py

balance:
	python balance.py

blockchain:
	python blockchain.py

received:
	python received.py

send:
	python send.py

getvault:
	python getvault.py

savings:
	python savings.py

vault_send:
	python vault_send.py 

vault_withdraw:
	python vault_withdraw.py 

vault_fast_withdraw:
	python vault_fast_withdraw.py 

vault_test:
	python test_vault.py 

info:
	python info.py

install:
	sudo apt-get install python-pip
	sudo pip install bitcoin-python
