address:
	python newaddress.py

account:
	python account.py

balance:
	python balance.py

blockchain:
	python blockchain.py

received:
	python received.py

send:
	python send.py 1JWZmf8cBZ8niAFSrJUSB3LvQGuBk56bdt 30

vault:
	python vault.py

savings:
	python savings.py

vault_send:
	python vault_send.py 1Bv4gbMo8mieCGkWrvaEiw1pVLZjomRbLK 1Dogc3GeFQMGCFtPA33BZ75ivfhtvM11BX 20 20
vault_withdraw:
	python vault_withdraw.py 4WnG6vAV1i6kJvopQ6iRfLDCKaWxQgeAUn 115vB6cU9bsy2sFQG7P1VsdDZ3tWSvMVuE 15 5

vault_fast_withdraw:
	python vault_fast_withdraw.py 4WnG6vAV1i6kJvopQ6iRfLDCKaWxQgeAUn 1Dogc3GeFQMGCFtPA33BZ75ivfhtvM11BX 4 4
vault_override:
	python vault_override.py 4SdcDeYzuQgN94w6959WC26vxbTVh7KHfR 1L6wmQ3pvXjbCDaBodx38UGN4xHyQDZd4F 20 5

info:
	python info.py

install:
	sudo apt-get install python-pip
	sudo pip install bitcoin-python
