address:
	python newaddress.py

account:
	python account.py

balance:
	python balance.py

received:
	python received.py

send:
	python send.py

vault_send:
	python vault_send.py 1KxrBZkWmXqaV8fbb287EosGB1mMg8njyN 16D91AN6f3kij96yb4FZAKzsT7QcLi5GEr 25 5

vault_withdraw:
	python vault_withdraw.py 1KxrBZkWmXqaV8fbb287EosGB1mMg8njyN 16D91AN6f3kij96yb4FZAKzsT7QcLi5GEr 25 5

vault_fast_withdraw:
	python vault_fast_withdraw.py 1KxrBZkWmXqaV8fbb287EosGB1mMg8njyN 16D91AN6f3kij96yb4FZAKzsT7QcLi5GEr 3

info:
	python info.py

install:
	sudo apt-get install python-pip
	sudo pip install bitcoin-python
